#!/bin/bash
#
#SBATCH --job-name=bbx_feat3
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 1:30:00
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/code/errors/feat3_bbx_%A_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/code/errors/feat3_bbx_%A_err.txt

cope="/projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/analysis/feat3/ses-1/cope${SLURM_ARRAY_TASK_ID}.fsf"
echo "running cope: ${cope}"
/projects/niblab/modules/software/fsl/5.0.10/bin/feat $cope
