#!/bin/bash
#SBATCH --job-name=BBX_FEAT1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 24:00:00
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/bids/code/error_files/feat1_bbx_%a_%A_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/bids/code/error_files/feat1_bbx_%a_%A_err.txt

if [ ${SLURM_ARRAY_TASK_ID} -lt 10 ]; then
    sub="sub-00${SLURM_ARRAY_TASK_ID}"
elif [ ${SLURM_ARRAY_TASK_ID} -lt 100 ]; then
    sub="sub-0${SLURM_ARRAY_TASK_ID}"
else
  sub="sub-${SLURM_ARRAY_TASK_ID}"
fi

RUN1=(/projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/$sub/func/Analysis/feat1/*run-1*.fsf)
RUN2=(/projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/$sub/func/Analysis/feat1/*run-2*.fsf)
RUN3=(/projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/$sub/func/Analysis/feat1/*run-3*.fsf)
RUN4=(/projects/niblab/bids_projects/Experiments/bbx/bids/derivatives/$sub/func/Analysis/feat1/*run-4*.fsf)


for f in ${RUN1[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done
wait
for f in ${RUN2[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done
wait
for f in ${RUN3[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done
wait
for f in ${RUN4[@]}; do
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done
